title: Kinderclub Warszawa
description: Landing Page of Saturday School Kinderclub Warszawa
sitename: Kinderclub Warszawa
baseurl: '/kinderclubwwa'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
